### ISSUE TITLE
PECL Release

### ISSUE THREAD

**Issue by remicollet** [websupport-sk/pecl-memcache#42]
If you maintain this extension and tag versions (4.0.x), please see to publish them on PECL.

**Comment by tomassrnka** [comment]
Yes I agree, let's do that. 

Requested account on pecl + need to fix some tests for php 7.0-7.2, see #46

**Comment by bobvandevijver** [comment]
@tomassrnka Any progress on this? As you can see in the doctrine/cache repository linked above this comment, you can revert the deprecation of the memcache driver by releasing it on PECL 😄

**Comment by tomassrnka** [comment]
@bobvandevijver  I wrote to pecl-dev list couple of weeks ago, so far no response. Maybe @remicollet  could help us with that? I would be more than happy to push this repo into PECL.

**Comment by Jan-E** [comment]
I replied to request in the pecl-dev list. Maybe we can shake things up a little bit.

**Comment by tomassrnka** [comment]
@Jan-E  thank you! 🥇

**Comment by pierrejoye** [comment]
Anything I can do? If you already have an account request, I can approve it
and add you to the current pecl memcache package.

**Comment by Jan-E** [comment]
http://news.php.net/php.pecl.dev/15838

**Comment by pierrejoye** [comment]
Approved

I need to add you to memcache, be sure to add you as well  to the
package.xml or you won't be able to do releases.

**Comment by tomassrnka** [comment]
I modified package.xml in the latest release. What should be the next steps? @pierrejoye Thanks

**Comment by tomassrnka** [comment]
@pierrejoye  / @Jan-E  any chance you could help me publish the extension on pecl? Thanks

**Comment by Jan-E** [comment]
I do not know the process and could not find a description online. @remicollet should know it best.

**Comment by bobvandevijver** [comment]
@tomassrnka Do you have any progress update on this?

**Comment by tomassrnka** [comment]
@bobvandevijver unfortunately no. I got accepted into PECL dev, but i can’t figure out how to become maintainer of the extension.

**Comment by bobvandevijver** [comment]
@tomassrnka Seems like you got to send an email to the developer mailing list? (https://pecl.php.net/takeover.php)

**Comment by tomassrnka** [comment]
@bobvandevijver thanks for the link, I wrote to the mailing list again. Let's hope this time it will be successful. Also I wrote to previous maintainer and he recommended to do the very same thing as he no longer maintains the original extension.

**Comment by oomujp** [comment]
Hello.

How is this issue progressing?

**Comment by tomassrnka** [comment]
@oomujp  Hi, I've just released latest version on pecl as stable. 4.0.5 works well with any PHP 7.x - https://pecl.php.net/package/memcache/4.0.5 Thanks everyone for help here!

**Comment by bobvandevijver** [comment]
Awesome! 

@tomassrnka It still shows "This package is not maintained, if you would like to take over please go to this page.", shouldn't that be removed?

**Comment by remicollet** [comment]
@tomassrnka notice that at least f76dff19e66e4c7ce547f70d5389d3b73303c1c7 is missing in the pecl archive (so 4.0.5 reports as 4.0.4 in phpinfo)

**Comment by tomassrnka** [comment]
@remicollet  thanks, fixed in 4.0.5.1 release, hopefully correct version is reported in both packages.xml and .h file

**Comment by tomassrnka** [comment]
@bobvandevijver edited description on pecl site, should be gone now, thx.

**Comment by glensc** [comment]
this project readme links to 4.0.5 which is 404:
- https://github.com/websupport-sk/pecl-memcache/commit/e940f20cd2c06b4643ebe9972759f92404ba8ca7
